.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend

stages:
  - build
  - quality
  - deploy
  - merge
  - release

merge_ready:
  stage: quality
  only:
    - merge_requests
  <<: *default_tag
  script:
    - mvn clean verify -U -Pquality_check -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  allow_failure: true

post_merge:
  stage: merge
  <<: *default_tag
  script:
    - mvn clean test -U -Pquality_check
  only:
    refs:
      - develop

build_package:
  stage: build
  <<: *default
  <<: *default_tag
  when: manual
  allow_failure: false
  script:
    - mvn clean package -U -DskipTests=true

deploy_snapshot:
  stage: deploy
  <<: *default
  <<: *default_tag
  when: manual
  script:
    - mvn deploy -DskipTests=true -Pdocker -Dmaven.install.skip=true
  allow_failure: false
  only:
    - web

release:
  <<: *default_tag
  stage: release
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull origin master
    - git checkout develop
    - git pull origin develop
    - mvn -U -Pdocker jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop